CREATE TABLE `도서관_대출` (
  `loan_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '대출 고유 ID',
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '회원 고유 ID (외래키)',
  `book_id` BIGINT UNSIGNED NOT NULL COMMENT '도서 고유 ID (외래키)',
  `loan_date` DATE DEFAULT '1970-01-01' COMMENT '대출 날짜',
  `return_date` DATE DEFAULT '1970-01-01' COMMENT '반납 예정 날짜',
  `actual_return_date` DATE DEFAULT '1970-01-01' COMMENT '실제 반납 날짜',
  `status` ENUM('활성', '비활성', '완료', '취소', '대기') DEFAULT '활성' COMMENT '대출 상태',
  `user_name` VARCHAR(100) NOT NULL COMMENT '회원 이름',
  `book_title` VARCHAR(200) NOT NULL COMMENT '도서 제목',
  `description` TEXT COMMENT '도서 설명',
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '대출 활성 여부',
  `duration` INT NOT NULL DEFAULT 0 COMMENT '대출 기간 (일 단위)',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '대출 기록 생성 시각',
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '대출 기록 수정 시각',
  `phone` CHAR(11) DEFAULT NULL COMMENT '회원 연락처 (숫자만)',
  `email` VARCHAR(255) DEFAULT NULL COMMENT '회원 이메일 주소',
  `penalty_fee` DECIMAL(10,2) DEFAULT 0.00 COMMENT '연체료',
  `payment_status` ENUM('완료', '대기', '취소', '실패') DEFAULT '대기' COMMENT '결제 상태',
  `order_status` ENUM('주문완료', '배송중', '배송완료', '취소') DEFAULT '주문완료' COMMENT '주문 상태',
  `property_type` ENUM('아파트', '빌라', '단독주택', '상가') DEFAULT '아파트' COMMENT '부동산 유형',
  `match_type` ENUM('리그', '컵대회', '친선경기', '플레이오프') DEFAULT '리그' COMMENT '경기 유형',
  PRIMARY KEY (`loan_id`),
  UNIQUE KEY `UK_user_book` (`user_id`, `book_id`),
  INDEX `IDX_loan_date` (`loan_date`),
  INDEX `IDX_return_date` (`return_date`)
) COMMENT='도서관 대출 기록 관리 테이블';
