CREATE TABLE `병원_진료` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '진료 고유 ID',
  `patient_id` BIGINT UNSIGNED NOT NULL COMMENT '환자 ID',
  `doctor_id` BIGINT UNSIGNED NOT NULL COMMENT '의사 ID',
  `appointment_date` DATE DEFAULT '1970-01-01' COMMENT '예약 날짜',
  `appointment_time` DATETIME DEFAULT '1970-01-01 00:00:00' COMMENT '예약 시간',
  `status` ENUM('활성', '비활성', '완료', '취소', '대기') DEFAULT '활성' COMMENT '진료 상태',
  `payment_status` ENUM('완료', '대기', '취소', '실패') DEFAULT '대기' COMMENT '결제 상태',
  `prescription` TEXT COMMENT '처방전 내용',
  `diagnosis` TEXT COMMENT '진단 내용',
  `notes` TEXT COMMENT '기타 메모',
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '진료 활성 여부',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '진료 기록 생성 시각',
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '진료 기록 수정 시각',
  `duration` INT NOT NULL DEFAULT 0 COMMENT '진료 시간 (분 단위)',
  `phone` CHAR(11) DEFAULT NULL COMMENT '환자 연락처 (숫자만)',
  `email` VARCHAR(255) DEFAULT NULL COMMENT '환자 이메일 주소',
  `name` VARCHAR(100) NOT NULL COMMENT '환자 이름',
  `title` VARCHAR(200) DEFAULT NULL COMMENT '진료 제목',
  `description` TEXT COMMENT '진료 상세 설명',
  `referral_source` ENUM('직접', '추천', '기타') DEFAULT '직접' COMMENT '진료 의뢰 경로',
  `follow_up_date` DATE DEFAULT '1970-01-01' COMMENT '후속 진료 날짜',
  PRIMARY KEY (`id`),
  INDEX `IDX_patient_id` (`patient_id`),
  INDEX `IDX_doctor_id` (`doctor_id`),
  INDEX `IDX_appointment_date` (`appointment_date`)
) COMMENT='병원 진료 정보 관리 테이블';
