CREATE TABLE `부동산_거래` (
  `transaction_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '거래 고유 ID',
  `property_id` BIGINT UNSIGNED NOT NULL COMMENT '부동산 ID',
  `agent_id` BIGINT UNSIGNED NOT NULL COMMENT '중개인 ID',
  `buyer_id` BIGINT UNSIGNED NOT NULL COMMENT '구매자 ID',
  `seller_id` BIGINT UNSIGNED NOT NULL COMMENT '판매자 ID',
  `transaction_date` DATETIME DEFAULT '1970-01-01 00:00:00' COMMENT '거래 날짜',
  `price` DECIMAL(15,2) NOT NULL DEFAULT 0.00 COMMENT '거래 가격',
  `status` ENUM('활성', '비활성', '완료', '취소', '대기') DEFAULT '활성' COMMENT '거래 상태',
  `payment_status` ENUM('완료', '대기', '취소', '실패') DEFAULT '대기' COMMENT '결제 상태',
  `order_status` ENUM('주문완료', '배송중', '배송완료', '취소') DEFAULT '주문완료' COMMENT '주문 상태',
  `property_type` ENUM('아파트', '빌라', '단독주택', '상가') DEFAULT '아파트' COMMENT '부동산 유형',
  `match_type` ENUM('리그', '컵대회', '친선경기', '플레이오프') DEFAULT '리그' COMMENT '경기 유형',
  `duration` INT NOT NULL DEFAULT 0 COMMENT '거래 지속 시간 (일 단위)',
  `title` VARCHAR(200) NOT NULL COMMENT '매물 제목',
  `description` TEXT COMMENT '매물 설명',
  `contact_phone` CHAR(11) DEFAULT NULL COMMENT '연락처 전화번호 (숫자만)',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '거래 생성 시각',
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '마지막 수정 시각',
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '거래 활성 여부',
  `location` VARCHAR(255) DEFAULT NULL COMMENT '부동산 위치',
  `area_size` DECIMAL(10,2) DEFAULT NULL COMMENT '면적 (제곱미터)',
  `floor` INT DEFAULT NULL COMMENT '층수',
  `year_built` YEAR DEFAULT NULL COMMENT '건축 연도',
  PRIMARY KEY (`transaction_id`),
  INDEX `IDX_property_id` (`property_id`),
  INDEX `IDX_agent_id` (`agent_id`),
  INDEX `IDX_buyer_id` (`buyer_id`),
  INDEX `IDX_seller_id` (`seller_id`)
) COMMENT='부동산 거래 정보 관리 테이블';
