CREATE TABLE `스포츠_경기` (
  `match_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '경기 고유 ID',
  `team_a` VARCHAR(100) NOT NULL COMMENT '팀 A 이름',
  `team_b` VARCHAR(100) NOT NULL COMMENT '팀 B 이름',
  `score_a` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '팀 A 점수',
  `score_b` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '팀 B 점수',
  `match_date` DATE DEFAULT '1970-01-01' COMMENT '경기 날짜',
  `match_time` DATETIME DEFAULT '1970-01-01 00:00:00' COMMENT '경기 시간',
  `location` VARCHAR(255) NOT NULL COMMENT '경기 장소',
  `referee` VARCHAR(100) DEFAULT NULL COMMENT '주심 이름',
  `duration` INT NOT NULL DEFAULT 0 COMMENT '경기 길이 (분 단위)',
  `status` ENUM('진행중', '완료', '취소', '대기') DEFAULT '대기' COMMENT '경기 상태',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 시각',
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '경기 활성 여부',
  `season` VARCHAR(100) DEFAULT NULL COMMENT '시즌',
  `league` VARCHAR(100) DEFAULT NULL COMMENT '리그 이름',
  `attendance` INT UNSIGNED DEFAULT 0 COMMENT '관중 수',
  `man_of_the_match` VARCHAR(100) DEFAULT NULL COMMENT '최우수 선수',
  `highlights` TEXT COMMENT '경기 하이라이트',
  `match_type` ENUM('리그', '컵대회', '친선경기', '플레이오프') DEFAULT '리그' COMMENT '경기 유형',
  `venue` VARCHAR(255) DEFAULT NULL COMMENT '경기장',
  PRIMARY KEY (`match_id`),
  INDEX `IDX_match_date` (`match_date`),
  INDEX `IDX_status` (`status`)
) COMMENT='스포츠 경기 정보 관리 테이블';
