CREATE TABLE `영화_정보` (
  `movie_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '영화 고유 ID',
  `title` VARCHAR(200) NOT NULL COMMENT '영화 제목',
  `director` VARCHAR(100) NOT NULL COMMENT '감독 이름',
  `cast` VARCHAR(255) NOT NULL COMMENT '주요 배우 목록',
  `genre` VARCHAR(100) NOT NULL COMMENT '장르',
  `release_date` DATE DEFAULT '1970-01-01' COMMENT '개봉일',
  `duration` INT NOT NULL DEFAULT 0 COMMENT '영화 길이 (분 단위)',
  `rating` DECIMAL(3,1) DEFAULT NULL COMMENT '영화 평점',
  `description` TEXT COMMENT '영화 설명',
  `language` VARCHAR(50) DEFAULT NULL COMMENT '언어',
  `country` VARCHAR(100) DEFAULT NULL COMMENT '제작 국가',
  `box_office` BIGINT UNSIGNED DEFAULT NULL COMMENT '박스 오피스 수익',
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '영화 활성 여부',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '정보 생성 시각',
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '정보 수정 시각',
  `status` ENUM('활성', '비활성', '완료', '취소', '대기') DEFAULT '활성' COMMENT '영화 상태',
  `payment_status` ENUM('완료', '대기', '취소', '실패') DEFAULT '대기' COMMENT '결제 상태',
  `order_status` ENUM('주문완료', '배송중', '배송완료', '취소') DEFAULT '주문완료' COMMENT '주문 상태',
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '사용자 고유 ID (외래키)',
  `film_code` VARCHAR(50) DEFAULT NULL COMMENT '영화 코드',
  `poster` BLOB COMMENT '영화 포스터 이미지 (바이너리 데이터)',
  PRIMARY KEY (`movie_id`),
  UNIQUE KEY `UK_title` (`title`),
  INDEX `IDX_director` (`director`),
  INDEX `IDX_release_date` (`release_date`)
) COMMENT='영화 정보 테이블';
