CREATE TABLE `온라인_쇼핑` (
  `order_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '주문 ID',
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '사용자 ID',
  `product_id` BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '상품 ID',
  `quantity` INT DEFAULT 1 COMMENT '수량',
  `price` DECIMAL(12,2) DEFAULT 0.00 COMMENT '가격',
  `order_status` ENUM('주문완료', '배송중', '배송완료', '취소') DEFAULT '주문완료' COMMENT '주문 상태',
  `delivery_address` VARCHAR(500) DEFAULT NULL COMMENT '배송 주소',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '주문 생성 시각',
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '마지막 수정 시각',
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '주문 활성 여부',
  `payment_status` ENUM('완료', '대기', '취소', '실패') DEFAULT '대기' COMMENT '결제 상태',
  `borrow_date` DATE DEFAULT '1970-01-01' COMMENT '대출일',
  `return_date` DATE DEFAULT '1970-01-01' COMMENT '반납일',
  `book_id` BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '도서 ID',
  `temperature` DECIMAL(4,1) DEFAULT 0.0 COMMENT '온도 (섭씨)',
  `humidity` INT DEFAULT 0 COMMENT '습도 (%)',
  `weather_condition` ENUM('맑음', '흐림', '비', '눈', '안개') DEFAULT '맑음' COMMENT '날씨 상태',
  `measured_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '측정 시간',
  `genre` VARCHAR(100) DEFAULT NULL COMMENT '장르',
  `artist_id` BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '아티스트 ID',
  `seat_number` VARCHAR(10) DEFAULT NULL COMMENT '좌석 번호',
  `appointment_date` DATETIME DEFAULT '1970-01-01 00:00:00' COMMENT '진료 예약일',
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `UK_user_product` (`user_id`, `product_id`),
  INDEX `IDX_created_at` (`created_at`),
  INDEX `IDX_order_status` (`order_status`)
) COMMENT='온라인 쇼핑 주문 관리 테이블';
