CREATE TABLE `항공권_예약` (
  `reservation_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '예약 고유 ID',
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '사용자 고유 ID',
  `flight_number` VARCHAR(10) NOT NULL COMMENT '항공편 번호',
  `departure_city` VARCHAR(100) NOT NULL COMMENT '출발 도시',
  `arrival_city` VARCHAR(100) NOT NULL COMMENT '도착 도시',
  `departure_date` DATE DEFAULT '1970-01-01' COMMENT '출발 날짜',
  `return_date` DATE DEFAULT '1970-01-01' COMMENT '귀국 날짜',
  `passenger_name` VARCHAR(100) NOT NULL COMMENT '승객 이름',
  `passenger_phone` CHAR(11) DEFAULT NULL COMMENT '승객 전화번호 (숫자만)',
  `passenger_email` VARCHAR(255) DEFAULT NULL COMMENT '승객 이메일',
  `seat_number` VARCHAR(10) COMMENT '좌석 번호',
  `total_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '총 가격',
  `payment_status` ENUM('완료', '대기', '취소', '실패') DEFAULT '대기' COMMENT '결제 상태',
  `status` ENUM('활성', '비활성', '완료', '취소', '대기') DEFAULT '활성' COMMENT '예약 상태',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '예약 시각',
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '마지막 수정 시각',
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '예약 활성 여부',
  `baggage_allowance` INT DEFAULT 0 COMMENT '수하물 허용량 (kg)',
  `meal_preference` ENUM('채식', '비채식', '글루텐프리', '무지방') DEFAULT '비채식' COMMENT '식사 선호도',
  `loyalty_program` VARCHAR(50) DEFAULT NULL COMMENT '회원 프로그램 코드',
  `notes` TEXT COMMENT '추가 메모',
  `ticket_type` ENUM('일반', '특가', '환불불가') DEFAULT '일반' COMMENT '티켓 유형',
  PRIMARY KEY (`reservation_id`),
  INDEX `IDX_user_id` (`user_id`),
  INDEX `IDX_flight_number` (`flight_number`)
) COMMENT='항공권 예약 정보 관리 테이블';
